### ISSUE TITLE
MemoryError when exectuting large sensitivity analysis

### ISSUE THREAD

**Issue by TobiasKAndersen** [BoldingBruggeman/parsac#11]
I am trying to execute a sensitivity analysis with 282000 model ensembles on a 128 core windows pc. Sampling step is fine, and run step is also fine until at the end of the execution (print to consol below shortened for brevity) and the pkl file does not include any results (Y values):

```
Starting model run...
Model run took 69.3 s.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\parsac.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\parsac\parsac_run.py", line 12, in main
    parsac.main()
  File "C:\ProgramData\Anaconda3\lib\site-packages\parsac\__init__.py", line 48, in main
    args.func(args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\parsac\sensitivity.py", line 225, in main
    Y = current_job.evaluate_ensemble([undoLogTransform(X[i, :], logscale) for i in range(X.shape[0])], stop_on_bad_result=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\parsac\job\shared.py", line 276, in evaluate_ensemble
    member, result = ppjob()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pp-1.6.4.4-py3.9.egg\pp.py", line 126, in __call__
    self.__unpickle()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pp-1.6.4.4-py3.9.egg\pp.py", line 144, in __unpickle
    six.print_(sout, end=' ')
MemoryError
ERROR: The process with PID 20100 could not be terminated.
Reason: The operation attempted is not supported.
ERROR: The process "4324" not found.
ERROR: The process with PID 8048 could not be terminated.
Reason: The operation attempted is not supported.
ERROR: The process with PID 14428 could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process with PID 5604 could not be terminated.
Reason: The operation attempted is not supported.
ERROR: The process with PID 9996 could not be terminated.
Reason: The operation attempted is not supported.
ERROR: The process with PID 15040 could not be terminated.
Reason: The operation attempted is not supported.
ERROR: The process with PID 8800 could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process with PID 10220 could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process "14996" not found.
ERROR: The process with PID 11660 could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process with PID 15124 could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process "19716" not found.
ERROR: The process with PID 8684 could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process "11440" not found.
...
```
To test, I have been running SA with LHS og delta method with fewer samples (between 200-300 samples) where parsac can complete the run step and the pkl file includes model results. Also, the calibration routine is running smoothly, so no problem there.

Is it a problem with internal memory capacity?

I was under the impression that parsac during 'sensitivity run' step writes results to the pkl file continously. Is this true?

I really hope someone can help out!

All the best,
Tobias

**Comment by jornbr** [comment]
Hi Tobias,

Yes, this definitely indicates that parsac has run out of memory. Your traceback suggests that this happened while it was interpreting the results of one of the worker processes (i.e., the results obtained after running a single sample). These results have two parts: the actual values of the target expression(s), and the text output of the worker (often the string representation of the parameters that are being evaluated). Thus, one way to reduce memory consumption would be to reduce the output of the worker. This can be done by passing -q/--quiet. Are you doing that already?

As for writing continuously to the pickle file: no, at present, parsac builds the full list of results in memory, and only then writes it to the pickle. That could be changed by switching to a custom output format (e.g., character-separated), but the problem is that in the end, SALib will need the entire set of results to be in memory in any case during the analysis step. Thus, memory-conserving tweaks to the pickling done as part of the run step are unlikely to provide a final solution.

Cheers,

Jorn

**Comment by TobiasKAndersen** [comment]
Hi Jorn,

Thanks for a quick reply!

Of course, I had not thought about the --quit function. I will try that and get back with - hopefully - results and no tracebacks.

Cheers,
Tobias

**Comment by jornbr** [comment]
Ok. If that helps, I will make a small tweak to the code that hopefully avoids keeping the text output (stdout/stderr) of every task in memory.

**Comment by jornbr** [comment]
Hi Tobias, is there any update on this? Did `--quiet` solve the problem?

**Comment by TobiasKAndersen** [comment]
Hi Jorn, 
Yes, we completed the run step with an updated pkl file after including '--quiet' 
Thank you for the help!
